"""Test program representation and rendering to a RISCOF-compatible assembly file.

Conventions for the generated body:
  * x31 is reserved: it holds the base of `fuzz_mem` (FUZZ_MEM_WORDS words, inside the
    signature region) so loads/stores done by the body are compared against Sail.
  * after the body, x1..x30 are dumped to `fuzz_regs`, also inside the signature.
  * the body is plain assembly: it is inserted after the C preprocessor has run, so no
    #define/#include and no // comments (use # for comments).
"""
import re
from dataclasses import dataclass

FUZZ_MEM_WORDS = 64

_TEMPLATE = """\
// Generated by the RS5 fuzzer: {name}
#include "model_test.h"
#include "arch_test.h"
RVTEST_ISA("{rvtest_isa}")

.section .text.init
.globl rvtest_entry_point
rvtest_entry_point:
RVMODEL_BOOT
RVTEST_CODE_BEGIN

#ifdef TEST_CASE_1

RVTEST_CASE(0,"{case_checks}def TEST_CASE_1=True;",fuzz)

    la x31, fuzz_mem

// ---- fuzz body ----
{body}
// ---- end of fuzz body ----

    la x31, fuzz_regs
{dump}
#endif

RVTEST_CODE_END
RVMODEL_HALT

RVTEST_DATA_BEGIN
.align 4
rvtest_data:
.word 0xbabecafe
RVTEST_DATA_END

RVMODEL_DATA_BEGIN
rvtest_sig_begin:
sig_begin_canary:
CANARY;

fuzz_regs:
    .fill 32,4,0xdeadbeef
fuzz_mem:
{mem_init}
sig_end_canary:
CANARY;
rvtest_sig_end:
RVMODEL_DATA_END
"""


@dataclass
class Program:
    name: str
    body: str                 # assembly lines, must not write x31
    march: str = 'rv32i_zicsr'
    rvtest_isa: str = 'RV32I'
    mem_init: tuple = ()      # initial words of fuzz_mem (rest is 0xdeadbeef)

    def case_checks(self):
        """RVTEST_CASE checks so RISCOF only selects this test for a DUT ISA that supports it."""
        exts = re.findall(r'Z[a-z0-9]+|[A-Z]', self.rvtest_isa[4:])  # skip 'RV32'
        checks = ['check ISA:=regex(.*32.*);']
        checks += ['check ISA:=regex(.*{}.*);'.format(e) for e in exts]
        return ''.join(checks)

    def mem_asm(self):
        words = list(self.mem_init)[:FUZZ_MEM_WORDS]
        mem = ['    .word 0x{:08x}'.format(w & 0xffffffff) for w in words]
        if len(words) < FUZZ_MEM_WORDS:
            mem.append('    .fill {},4,0xdeadbeef'.format(FUZZ_MEM_WORDS - len(words)))
        return '\n'.join(mem)

    def render(self, body=None, mem_init=None):
        """Full .S file. body/mem_init override the program's own (used to build skeletons)."""
        dump = '\n'.join('    sw x{0}, {1}(x31)'.format(r, 4 * (r - 1)) for r in range(1, 31))
        return _TEMPLATE.format(name=self.name, rvtest_isa=self.rvtest_isa,
                                case_checks=self.case_checks(),
                                body=self.body if body is None else body,
                                dump=dump,
                                mem_init=self.mem_asm() if mem_init is None else mem_init)

    def skeleton_key(self):
        """Programs with the same key share the same preprocessed skeleton."""
        return (self.march, self.rvtest_isa)
